server:
  port: 8080
spring:
  application:
    name: spring-cloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:1101/eureka,http://eureka2:1102/eureka/
  instance:
    instance-id: zwz.cn
    prefer-ip-address: true
zuul:
  prefix: /api
  routes:
    user.serviceId: provider
    user.path: /user/**
  ignored-services: provider # 设置不能使用原有路径访问,必须使用网关地址访问
# 原有路径 http://localhost:8080/api/provider/user/list?name=sds&token=dsd:
# 网关地址 http://localhost:8080/api/user/user/list?name=sds&token=dsd