server:
  port: 1301
spring:
  application:
    name: zwz-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1101/eureka,http://localhost:1102/eureka
  instance:
    # 该实例给服务中心发送心跳的间隔时间，用于表明该服务实例可用
    lease-expiration-duration-in-seconds: 10
    # 服务中心删除此服务实例的等待时间(秒为单位),时间间隔为最后一次服务中心接受到的心跳时间
    lease-renewal-interval-in-seconds: 2
# 监控
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream